#!/usr/bin/env python3
"""Step 9, arm b -- generate the register rows for the marked originals (0124, then 0125).

THE ROWS ARE MEASURED, SO THEY FOLLOW THE RULING WITHOUT BEING TOLD ABOUT IT. Every value is the
difference between the marked original and WHATEVER THE CORRECTED EMISSION CURRENTLY HOLDS, so
when decisions/0125 moved the corrected CI endpoints a second time this generator re-derived the
set rather than needing an edit: two values fell under the control's 5e-5 tolerance and one rose
above it. The block name still says 0124 because renaming a marker orphans the block it
delimits; the reason text names both rulings.

WHY. CLAUDE.md: "Register every superseded value the move creates, not just the one that
prompted the correction." decisions/0124 supersedes the adopted arm's CI endpoints inside
artifacts/step9-headline-b.{json,md}. Without rows, src/check_surfaces.py cannot see them --
it "passed because it never looked for them", which is exactly how 0123's gap read.

AND WITHOUT ROWS THE STAMPING CANNOT BE PROBED. "A superseded value reintroduced unmarked must
drive exit 1" is a statement about the register; a stamp on a value nothing looks for silences
nothing, and a clean run would prove only that the control was blind.

NO VALUE IN THIS FILE IS TYPED. Every one is MEASURED off the two artifacts by the same
old-vs-corrected diff the stamper uses, and every candidate is verified to OCCUR in the file it
is scoped to before a row is written -- a row that matches nothing is inert and CLAUDE.md
forbids it. The block between the markers is rewritten wholesale on each run.

Run:  python3 src/step9_b_13_register_0124.py
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))
import step9_b_6_stamp_superseded as M                                          # noqa: E402

REGISTER = os.path.join(ROOT, "src", "step7_register.py")
BEGIN = "# >>> STEP9-B 0124 ROWS -- GENERATED BY src/step9_b_13_register_0124.py, DO NOT EDIT BY HAND"
END = "# <<< STEP9-B 0124 ROWS"
# THE FRAGMENT IS THE FULL RELATIVE PREFIX, NOT THE BASENAME. check_surfaces.py scopes a row
# with `frag in f` against the path as listed in SURFACES, and `step9-headline-b` also matches
# processed/step9/b/preview/step9-headline-b.json -- the CORRECTED preview. The first run of
# this generator used the basename and drove exit 1 on four preview leaves carrying CORRECT
# figures. A file-scoped row is only as scoped as its fragment.
FRAG = "artifacts/step9-headline-b"

WHY = ("arm b W108_s2_finale CI endpoint or CI-derived figure, produced under the per-mask "
       "frame and per-group re-seed that decisions/0124 fixed against AND the `multinomial` "
       "draw mechanism that decisions/0125 fixed against; corrected value in "
       "step9-headline-corrected-2026-08-21-b (0124, 0125)")

TOL = 5e-5
NUM = re.compile(r"(?<![\w.])(-?\d{1,3}(?:,\d{3})*(?:\.\d+)?|-?\d+\.\d+)(?![\w])")


def json_numbers(path):
    out = []

    def walk(o):
        if isinstance(o, dict):
            for v in o.values():
                walk(v)
        elif isinstance(o, list):
            for v in o:
                walk(v)
        elif isinstance(o, (int, float)) and not isinstance(o, bool):
            out.append(float(o))
    walk(json.load(open(path)))
    return out


def moved_json_values():
    """The 29 adopted-arm numeric leaves whose value differs from the corrected emission."""
    old = json.load(open(M.COMMITTED_HEADLINE))
    new = json.load(open(M.CORRECTED_HEADLINE))
    fin = [i for i, a in enumerate(old["arms"]) if a["clock_origin"] == "s2_finale"]
    iv = [i for i, v in enumerate(old["declared_intervals"]) if "s2_finale" in v["interval_id"]]
    regions = ["$.arms[%d]" % fin[0]] + ["$.declared_intervals[%d]" % i for i in iv]
    vals = []
    for rp in regions:
        ol = dict(M.leaves(M.resolve(old, rp), rp))
        nl = dict(M.leaves(M.resolve(new, rp), rp))
        for p, v in ol.items():
            if M.is_number(v) and nl.get(p) != v:
                vals.append((round(float(v), 6), p))
    return vals


def marked_md_numbers():
    """Numbers inside cells this arm marked ·SUPERSEDED-0124, and where they sit."""
    inside, outside = {}, {}
    for ln in open(M.COMMITTED_MD).read().split("\n"):
        if not ln.startswith("|"):
            continue
        for cell in ln.split("|"):
            bucket = inside if M.MD_ROW_MARK_0124.strip() in cell else outside
            for m in NUM.finditer(cell.replace(M.MD_ROW_MARK_0124, "")):
                bucket.setdefault(round(float(m.group(1).replace(",", "")), 6), 0)
                bucket[round(float(m.group(1).replace(",", "")), 6)] += 1
    return inside, outside


def near_any(v, pool):
    return any(abs(v - p) < TOL for p in pool)


def unmarked_json_numbers(path, marked_paths):
    """Every numeric leaf in the file that this arm did NOT mark, with its path."""
    root = json.load(open(path))
    return [(float(v), p) for p, v in M.leaves(root, "$")
            if M.is_number(v) and p not in marked_paths]


def main():
    jvals = moved_json_values()
    json_pool = {v for v, _ in jvals}
    inside, outside = marked_md_numbers()

    rows, dropped_inert, excluded_integers, collisions = {}, [], {}, []
    indistinguishable = []

    # *** THE POOL A ROW MUST NOT COLLIDE WITH. ***
    # A register row matches NUMERICALLY at tol 5e-5. So a row is only usable if its value is
    # further than that from every number sitting at an UNMARKED position in the same two
    # files, AND from the CORRECTED value that replaced it. Three of this arm's 24 movements
    # are smaller than 5e-5 -- the DERIV never-started endpoints move by 4.5e-6 and 7.2e-6 --
    # so a row on them would fire on the corrected figure as readily as on the superseded one.
    # A control that cannot tell the two apart is not policing anything; it is manufacturing
    # false positives. Those values are UNPOLICED and said so, not registered and hoped for.
    marked_paths = {p for _, p in jvals}
    protect = [v for v, _ in unmarked_json_numbers(M.COMMITTED_HEADLINE, marked_paths)]
    protect += list(outside)
    corrected_pool = json_numbers(M.CORRECTED_HEADLINE)

    # (1) the JSON leaves. Scoped to the headline JSON and to its .md, which renders the same
    #     figures at 4 dp -- both are matched, because near() works at 5e-5.
    json_nums = json_numbers(M.COMMITTED_HEADLINE)
    md_nums = set(inside) | set(outside)
    for v, path in sorted(jvals):
        if not near_any(v, json_nums):
            dropped_inert.append((v, path, "not found in the headline JSON"))
            continue
        if near_any(v, protect) or near_any(v, corrected_pool):
            indistinguishable.append((v, path))
            continue
        rows[(FRAG, v)] = WHY

    # (2) figures the .md renders that have NO JSON leaf -- the CI widths and the movement
    #     widths, which the emitter computes at write time. A superseded figure with no leaf
    #     is invisible to the numeric half unless it is registered from the text.
    for v, n in sorted(inside.items()):
        if near_any(v, json_pool):
            continue                       # already covered by (1)
        if float(v).is_integer():
            # the ratio multipliers -- 12x, 33x, 15x, 337x, 42x. Small integers, and the
            # exclusion is measured rather than assumed: see excluded_integers below.
            excluded_integers[v] = sum(c for w, c in list(inside.items()) + list(outside.items())
                                       if abs(w - v) < TOL)
            continue
        if near_any(v, corrected_pool):
            indistinguishable.append((v, "an .md-only width"))
            continue
        if any(abs(w - v) < TOL for w in outside):
            # the same figure also sits on an UNMARKED cell somewhere in this file. Either it
            # has a legitimate reading there or it is an unmarked superseded figure. Neither is
            # for this script to decide, so it is REPORTED and NOT registered.
            collisions.append(v)
            continue
        rows[(FRAG, v)] = WHY

    src = open(REGISTER).read()
    body = [BEGIN,
            "# %d rows. Every value MEASURED off artifacts/step9-headline-b.{json,md} by diffing" % len(rows),
            "# the adopted arm against the corrected emission; none typed. Scoped to `step9-headline-b`,",
            "# which matches that JSON and its .md and NO other file in the study, so a collision",
            "# elsewhere cannot make a row fire. Each value was verified to OCCUR in its file before",
            "# the row was written: a row that matches nothing is inert.",
            "#",
            "# THESE ROWS DO NOT FIRE ON THE MARKED ORIGINALS -- the 0124 stamps are field-scoped and",
            "# check_surfaces.stamped_field_paths() honours exactly the fields each names, and the .md",
            "# marks sit on the emitting line. They fire if a value is REINTRODUCED unmarked.",
            "#",
            "# DELIBERATELY UNREGISTERED, stated rather than left silent: the ratio multipliers"]
    body += ["#   %g -- occurs %d times in these two files alone" % (v, n)
             for v, n in sorted(excluded_integers.items())]
    body += ["# They are small integers; registering them would flag correct counts in the same file.",
             "#",
             "# ALSO UNREGISTERED AND THEREFORE UNPOLICED -- %d values whose movement under 0124 is" % len(indistinguishable),
             "# SMALLER THAN THE CONTROL'S OWN MATCHING TOLERANCE (5e-5), so a row on them would fire",
             "# on the corrected figure as readily as on the superseded one:"]
    body += ["#   %r  (%s)" % (v, p) for v, p in sorted(indistinguishable)]
    body += ["SUPERSEDED_IN.update({"]
    body += ['    ("%s", %s): "%s",' % (f, repr(v), WHY) for (f, v) in sorted(rows)]
    body += ["})", END]
    block = "\n".join(body)

    if BEGIN in src:
        head, _, rest = src.partition(BEGIN)
        _, _, tail = rest.partition(END)
        src = head + block + tail
    else:
        anchor = "\n# ------------------------------------------------------------------------------- adopted"
        assert src.count(anchor) == 1
        src = src.replace(anchor, "\n\n" + block + "\n" + anchor, 1)
    open(REGISTER, "w").write(src)

    print("rows written: %d" % len(rows))
    print("dropped as INERT (value not present in the file): %d %s"
          % (len(dropped_inert), dropped_inert))
    print("excluded integers (ratio multipliers), with in-file occurrence counts: %s"
          % excluded_integers)
    print("REPORTED, not registered -- also present on an UNMARKED cell in the same file: %s"
          % collisions)
    print("UNPOLICED -- movement smaller than the control's 5e-5 tolerance: %d %s"
          % (len(indistinguishable), sorted(indistinguishable)))
    print("\ncoverage: %d moved JSON leaves examined, %d distinct numbers inside marked .md "
          "cells, %d distinct numbers on unmarked .md cells" % (len(jvals), len(inside), len(outside)))


if __name__ == "__main__":
    main()
